### ISSUE TITLE
Review the bins parameter in ST_HISTOGRAM function

### ISSUE THREAD

**Issue by archelogos** [Vizzuality/sql2gee#9]
When the ST_HISTOGRAM function is executed defining a specific number of bins (with a number), it works fine.

```sql = "SELECT ST_HISTOGRAM(rast, 1, 10, true) FROM srtm90_v4"```

If instead of that, that parameter is set to 'auto':

```sql = "SELECT ST_HISTOGRAM(rast, 1, auto, true) FROM srtm90_v4"```

 It responses the following error:

"invalid literal for int() with base 10: 'auto'"

Thanks!

**Comment by benlaken** [comment]
Ok, working on it now!

**Comment by benlaken** [comment]
In the latest version (0.1.0) the bug seems to be squashed already. I added a test to catch this bug if it comes back.
